language: cpp
before_script:
- sudo apt-get install libgtest-dev -y
- OLD_PATH=$PWD
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- cd $OLD_PATH
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umaxan1980:$BINTRAY_API_KEY "https://api.bintray.com/content/maxan1980/otus-cpp/otus/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  on:
     branch: hw_1_1